var routes = [ 
{"id":"MTA NYCT_BX10",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Riverdale Av / W 231st St / Jerome Av",
"longName":"Riverdale - Norwood",
"shortName":"Bx10",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx010cur.pdf"},
{"id":"MTA NYCT_BX11",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Claremont Pkwy / E 170th St",
"longName":"West Farms Rd - Southern Blvd & GW Bridge",
"shortName":"Bx11",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx011cur.pdf"},
{"id":"MTA NYCT_BX12",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Pelham Pkwy / Fordham Rd",
"longName":"Pelham Pkwy - Fordham Rd",
"shortName":"Bx12",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx012cur.pdf"},
{"id":"MTA NYCT_BX13",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Ogden Av / W 181st St",
"longName":"George Washington Bridge - Yankee Stadium",
"shortName":"Bx13",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx013cur.pdf"},
{"id":"MTA NYCT_S55",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Bloomingdale Rd / Annadale Rd / Richmond Av",
"longName":"Rossville - Staten Island Mall",
"shortName":"S55",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s055cur.pdf"},
{"id":"MTA NYCT_S54",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Manor Rd",
"longName":"West New Brighton - Eltingville",
"shortName":"S54",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s054cur.pdf"},
{"id":"MTA NYCT_BX15",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via 3rd Av / 125th St",
"longName":"Fordham Plaza - Manhattanville",
"shortName":"Bx15",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx015cur.pdf"},
{"id":"MTA NYCT_S53",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Verrazano-Narrows Bridge / Clove Rd",
"longName":"Port Richmond - Bay Ridge",
"shortName":"S53",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s053cur.pdf"},
{"id":"MTA NYCT_BX16",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via E 233rd St / Nereid Av",
"longName":"Pelham - Norwood",
"shortName":"Bx16",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx016cur.pdf"},
{"id":"MTA NYCT_S52",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Tompkins Av / Cebra Av / Jersey St",
"longName":"St. George - Staten Island Univ. Hospital",
"shortName":"S52",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s052cur.pdf"},
{"id":"MTA NYCT_BX17",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Crotona Av / Prospect Av",
"longName":"Fordham Plaza - Port Morris",
"shortName":"Bx17",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx017cur.pdf"},
{"id":"MTA NYCT_S59",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Richmond Av",
"longName":"Port Richmond - Tottenville",
"shortName":"S59",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s059cur.pdf"},
{"id":"MTA NYCT_BX18",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via Macombs Rd",
"longName":"Tremont - Morris Heights",
"shortName":"Bx18",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx018cur.pdf"},
{"id":"MTA NYCT_BX19",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Southern Blvd / E 149th St",
"longName":"NY Botanical Garden - Riverbank Park",
"shortName":"Bx19",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx019cur.pdf"},
{"id":"MTA NYCT_S57",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via Rockland Av / Brielle Av / Bradley Av",
"longName":"Port Richmond - New Dorp",
"shortName":"S57",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s057cur.pdf"},
{"id":"MTA NYCT_S56",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via Richmond Av / Arthur Kill Rd / Foster Rd",
"longName":"Huguenot - Staten Island Mall",
"shortName":"S56",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s056cur.pdf"},
{"id":"MTA NYCT_BX1",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via Grand Concourse / E 138th St",
"longName":"Riverdale - Mott Haven",
"shortName":"Bx1",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx001cur.pdf"},
{"id":"MTA NYCT_X22A",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Outerbridge Park & Ride / West Shore Pkwy",
"longName":"Staten Island - Manhattan Express",
"shortName":"X22A",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x022cur.pdf"},
{"id":"MTA NYCT_BX5",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Bruckner Blvd Svc Rd / Story Av",
"longName":"Pelham Bay - West Farms Rd & Southern Blvd",
"shortName":"Bx5",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx005cur.pdf"},
{"id":"MTA NYCT_BX4",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Westchester Av",
"longName":"Westchester Sq - The Hub",
"shortName":"Bx4",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx004cur.pdf"},
{"id":"MTA NYCT_S51",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Bay St / Father Capodanno Blvd",
"longName":"St. George - West Shore Plaza",
"shortName":"S51",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s051cur.pdf"},
{"id":"MTA NYCT_X17A",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Richmond Av / Annandale Rd",
"longName":"Staten Island - Lower Manhattan Express",
"shortName":"X17A",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x017cur.pdf"},
{"id":"MTA NYCT_BX3",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via University Av / W 181st St",
"longName":"Riverdale - George Washington Bridge",
"shortName":"Bx3",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx003cur.pdf"},
{"id":"MTA NYCT_BX2",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Grand Concourse / E 149th St",
"longName":"Kingsbridge Heights - Mott Haven",
"shortName":"Bx2",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bkln/b002cur.pdf"},
{"id":"MTA NYCT_X17J",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Richmond Av / Arden Av / Huguenot Av",
"longName":"Staten Island - Midtown Manhattan Express",
"shortName":"X17J",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x017cur.pdf"},
{"id":"MTA NYCT_BX6",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via E 161st St / E 163rd St",
"longName":"Hunts Point - Riverside Dr",
"shortName":"Bx6",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx006cur.pdf"},
{"id":"MTA NYCT_M34A+",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"Select Bus Service via 34th St Crosstown",
"longName":"Waterside - Port Authority Terminal",
"shortName":"M34A-SBS",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/manh/m034scur.pdf"},
{"id":"MTA NYCT_S42",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via St Marks Pl / Jersey St",
"longName":"St. George - Clyde Place",
"shortName":"S42",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s052cur.pdf"},
{"id":"MTA NYCT_BX7",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Riverdale Av / Broadway",
"longName":"Riverdale - Washington Heights",
"shortName":"Bx7",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx007cur.pdf"},
{"id":"MTA NYCT_BX8",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Bronxwood Av / Williamsbridge Rd / Crosby Av",
"longName":"Williamsbridge - Locust Point",
"shortName":"Bx8",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx008cur.pdf"},
{"id":"MTA NYCT_S44",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Richmond Av",
"longName":"St. George - Staten Island Mall",
"shortName":"S44",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s044cur.pdf"},
{"id":"MTA NYCT_BX9",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Broadway / Kingsbridge Rd / Southern Blvd",
"longName":"Riverdale - West Farms Sq",
"shortName":"Bx9",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx009cur.pdf"},
{"id":"MTA NYCT_S46",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Castleton Av",
"longName":"St. George - West Shore Plaza",
"shortName":"S46",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s046cur.pdf"},
{"id":"MTA NYCT_S48",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Forest Av",
"longName":"St. George - Mariners Harbor",
"shortName":"S48",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s048cur.pdf"},
{"id":"MTA NYCT_X10B",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Richmond Av / Gannon Av",
"longName":"Staten Island - Manhattan Express",
"shortName":"X10B",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x010cur.pdf"},
{"id":"MTA NYCT_S40",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Richmond Terrace",
"longName":"St. George - Goethals Rd North",
"shortName":"S40",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s040cur.pdf"},
{"id":"MTA NYCT_M34+",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"Select Bus Service via 34th St Crosstown",
"longName":"East Side - Javits Center",
"shortName":"M34-SBS",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/manh/m034scur.pdf"},
{"id":"MTA NYCT_S78",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Hylan Blvd",
"longName":"St. George - Bricktown Mall",
"shortName":"S78",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s078cur.pdf"},
{"id":"MTA NYCT_S76",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Richmond Rd / New Dorp Ln",
"longName":"St. George - Oakwood",
"shortName":"S76",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s076cur.pdf"},
{"id":"MTA NYCT_S74",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Richmond Rd / Arthur Kill Rd",
"longName":"St. George - Bricktown Mall",
"shortName":"S74",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s074cur.pdf"},
{"id":"MTA NYCT_S66",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via Victory Blvd / Jewett Av",
"longName":"St. George - Port Richmond",
"shortName":"S66",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s066cur.pdf"},
{"id":"MTA NYCT_S61",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Victory Blvd / Bradley Av",
"longName":"St. George - Staten Island Mall",
"shortName":"S61",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s061cur.pdf"},
{"id":"MTA NYCT_X10",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Richmond Av / Gannon Av",
"longName":"Staten Island - Manhattan Express",
"shortName":"X10",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x010cur.pdf"},
{"id":"MTA NYCT_S62",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Victory Blvd",
"longName":"St. George - Travis",
"shortName":"S62",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s062cur.pdf"},
{"id":"MTA NYCT_X15",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Richmond Rd / Arthur Kill Rd",
"longName":"Staten Island - Lower Manhattan Express",
"shortName":"X15",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x015cur.pdf"},
{"id":"MTA NYCT_X17",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Richmond Av / Arden Av / Huguenot Av",
"longName":"Staten Island - Manhattan Express",
"shortName":"X17",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x017cur.pdf"},
{"id":"MTA NYCT_X12",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Watchogue Rd / Forest Av / South Av",
"longName":"Staten Island - Manhattan Express",
"shortName":"X12",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x012cur.pdf"},
{"id":"MTA NYCT_X11",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Victory Blvd / Gannon Av",
"longName":"Staten Island - Lower Manhattan Express",
"shortName":"X11",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x010cur.pdf"},
{"id":"MTA NYCT_X14",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Port Richmond Av / Forest Av / Narrows Rd",
"longName":"Staten Island - Manhattan Express",
"shortName":"X14",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x014cur.pdf"},
{"id":"MTA NYCT_S98",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Forest Av (S48 Limited)",
"longName":"St. George - Mariners Harbor LTD",
"shortName":"S98",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s048cur.pdf"},
{"id":"MTA NYCT_S96",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Castleton Av (S46 Limited)",
"longName":"St. George - West Shore Plaza LTD",
"shortName":"S96",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s046cur.pdf"},
{"id":"MTA NYCT_BX4A",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Metropolitan Oval / Westchester Av",
"longName":"Westchester Sq - The Hub",
"shortName":"Bx4A",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx004cur.pdf"},
{"id":"MTA NYCT_X19",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Huguenot Av / Arden Av / W Shore Expwy",
"longName":"Staten Island - Manhattan Express",
"shortName":"X19",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x017cur.pdf"},
{"id":"MTA NYCT_S79+",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"Select Bus Service via Verrazano-Narrows Bridge / Hylan Blvd",
"longName":"Staten Island Mall - Bay Ridge",
"shortName":"S79-SBS",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s079scur.pdf"},
{"id":"MTA NYCT_BX41+",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via East Gun Hill Rd/White Plains Rd",
"longName":"Williamsbridge - Select Bus Service",
"shortName":"Bx41-SBS",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx041scur.pdf"},
{"id":"MTA NYCT_X22",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Bloomingdale Rd / Amboy Rd",
"longName":"Staten Island - Manhattan Express",
"shortName":"X22",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x022cur.pdf"},
{"id":"MTA NYCT_S91",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Victory Blvd / Bradley Av (S61 Limited)",
"longName":"St. George - Staten Island Mall LTD",
"shortName":"S91",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s061cur.pdf"},
{"id":"MTA NYCT_S90",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Richmond Terrace (S40 Limited)",
"longName":"St. George - Goethals Rd North LTD",
"shortName":"S90",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s040cur.pdf"},
{"id":"MTA NYCT_S94",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Richmond Av (S44 Limited)",
"longName":"St. George - Staten Island Mall LTD",
"shortName":"S94",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s044cur.pdf"},
{"id":"MTA NYCT_S93",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Verrazano-Narrows / Victory",
"longName":"College of Staten Island - Bay Ridge LTD",
"shortName":"S93",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s093cur.pdf"},
{"id":"MTA NYCT_S92",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Victory Blvd (S62 Limited)",
"longName":"St. George - Travis LTD",
"shortName":"S92",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s062cur.pdf"},
{"id":"MTA NYCT_S86",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Richmond Rd / New Dorp Ln (S76 Limited)",
"longName":"St. George - Oakwood LTD",
"shortName":"S86",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s076cur.pdf"},
{"id":"MTA NYCT_S89",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Richmond Av (S59 Limited)",
"longName":"Eltingville - Bayonne LTD",
"shortName":"S89",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s089cur.pdf"},
{"id":"MTA NYCT_BX46",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Barretto PK",
"longName":"Prospect Av - Westchester Av / Hunts Point Market",
"shortName":"Bx46",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx046cur.pdf"},
{"id":"MTA NYCT_M100",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via Broadway / Amsterdam Av / 125th St",
"longName":"Inwood - East Harlem",
"shortName":"M100",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/manh/m100cur.pdf"},
{"id":"MTA NYCT_BX41",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Webster Av / E Gun Hill Rd",
"longName":"Williamsbridge - The Hub",
"shortName":"Bx41",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx041cur.pdf"},
{"id":"MTA NYCT_BX40",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Tremont Av Crosstown",
"longName":"Throgs Neck - River Park Towers",
"shortName":"Bx40",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx040cur.pdf"},
{"id":"MTA NYCT_X30",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Forest Av / Victory Blvd",
"longName":"Staten Island - Manhattan Express",
"shortName":"X30",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x030cur.pdf"},
{"id":"MTA NYCT_BX42",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Tremont Av Crosstown",
"longName":"Throgs Neck - River Park Towers",
"shortName":"Bx42",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx040cur.pdf"},
{"id":"MTA NYCT_S81",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via Bay St / Father Capodanno Blvd (S51 Limited)",
"longName":"St. George - Grant City LTD",
"shortName":"S81",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s051cur.pdf"},
{"id":"MTA NYCT_X31",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Travis Av / Forest Hill Rd",
"longName":"Staten Island - Manhattan Express",
"shortName":"X31",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x031cur.pdf"},
{"id":"MTA NYCT_S84",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Richmond Rd / Arthur Kill Rd (S74 Limited)",
"longName":"St. George - Bricktown Mall LTD",
"shortName":"S84",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/staten/s074cur.pdf"},
{"id":"MTA NYCT_X7",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Giffords Ln / Nelson Av / Hylan Blvd",
"longName":"Staten Island - Manhattan Express",
"shortName":"X7",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x001cur.pdf"},
{"id":"MTA NYCT_X4",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Richmond Av / Hylan Blvd",
"longName":"Staten Island - Lower Manhattan Express",
"shortName":"X4",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x001cur.pdf"},
{"id":"MTA NYCT_X5",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Richmond Av / Hylan Blvd",
"longName":"Staten Island - Midtown Manhattan Express",
"shortName":"X5",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x001cur.pdf"},
{"id":"MTA NYCT_BX39",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via White Plains Rd",
"longName":"Wakefield - Clasons Pt",
"shortName":"Bx39",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx039cur.pdf"},
{"id":"MTA NYCT_X2",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Hylan Blvd",
"longName":"Staten Island - Midtown Manhattan Express",
"shortName":"X2",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x001cur.pdf"},
{"id":"MTA NYCT_BX38",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via E Gun Hill Rd / Co-op City Blvd",
"longName":"Co-op City Bay Plaza - Norwood",
"shortName":"Bx38",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bkln/b038cur.pdf"},
{"id":"MTA NYCT_X3",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Hylan Blvd",
"longName":"Staten Island - Lower Manhattan Express",
"shortName":"X3",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x001cur.pdf"},
{"id":"MTA NYCT_BX36",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via E 174th / E 180th St",
"longName":"Soundview - George Washington Bridge",
"shortName":"Bx36",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx036cur.pdf"},
{"id":"MTA NYCT_BX35",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via E 167th / W 181st St",
"longName":"West Farms Rd & Southern Blvd - GW Bridge",
"shortName":"Bx35",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx035cur.pdf"},
{"id":"MTA NYCT_X1",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Hylan Blvd / Richmond Av",
"longName":"Staten Island - Manhattan Express",
"shortName":"X1",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x001cur.pdf"},
{"id":"MTA NYCT_X42",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Watchogue Rd / Forest Av / South Av",
"longName":"Staten Island - Midtown Manhattan Express",
"shortName":"X42",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x012cur.pdf"},
{"id":"MTA NYCT_BX34",
"textColor":"FFFFFF",
"color":"B933AD",
"description":"via Bainbridge Av",
"longName":"Woodlawn - Fordham Center",
"shortName":"Bx34",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx034cur.pdf"},
{"id":"MTA NYCT_BX33",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via E 138th St / W 135th St",
"longName":"Port Morris - Harlem",
"shortName":"Bx33",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx033cur.pdf"},
{"id":"MTA NYCT_BX32",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via Morris Av / Jerome Av",
"longName":"Kingsbridge VA Hospital - Mott Haven",
"shortName":"Bx32",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx032cur.pdf"},
{"id":"MTA NYCT_BX31",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Eastchester Rd",
"longName":"Woodlawn - Westchester Sq",
"shortName":"Bx31",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx031cur.pdf"},
{"id":"MTA NYCT_BX30",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Boston Rd / E Gun Hill Rd",
"longName":"Co-op City Section 5 - Norwood",
"shortName":"Bx30",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx030cur.pdf"},
{"id":"MTA NYCT_B63",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"via 5th Av / Atlantic Av",
"longName":"Bay Ridge - Cobble Hill",
"shortName":"B63",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bkln/b063cur.pdf"},
{"id":"MTA NYCT_B61",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via Van Brunt St / Columbia St / 9th St",
"longName":"Park Slope - Downtown Brooklyn",
"shortName":"B61",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bkln/b061cur.pdf"},
{"id":"MTA NYCT_X9",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Hylan Blvd",
"longName":"Staten Island - Manhattan Express",
"shortName":"X9",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x001cur.pdf"},
{"id":"MTA NYCT_X8",
"textColor":"FFFFFF",
"color":"00933C",
"description":"via Giffords Ln / Nelson Av / Hylan Blvd",
"longName":"Staten Island - Lower Manhattan Express",
"shortName":"X8",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/xpress/x001cur.pdf"},
{"id":"MTA NYCT_BX29",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via City Island Rd / City Island Av",
"longName":"City Island - Co-op City Bay Plaza",
"shortName":"Bx29",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx029cur.pdf"},
{"id":"MTA NYCT_BX28",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via E Gun Hill Rd / Bartow Av",
"longName":"Co-op City Section 5 - Fordham Center",
"shortName":"Bx28",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx028cur.pdf"},
{"id":"MTA NYCT_BX24",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via Country Club Loop",
"longName":"Pelham Bay - Country Club Loop",
"shortName":"Bx24",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx024cur.pdf"},
{"id":"MTA NYCT_BX27",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via Westchester Av / Soundview Av",
"longName":"Clasons Pt - West Farms Rd & Southern Blvd",
"shortName":"Bx27",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx027cur.pdf"},
{"id":"MTA NYCT_BX26",
"textColor":"FFFFFF",
"color":"FAA61A",
"description":"via Allerton Av",
"longName":"Co-op City Section 5 - Bedford Park",
"shortName":"Bx26",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx026cur.pdf"},
{"id":"MTA NYCT_BX21",
"textColor":"FFFFFF",
"color":"6CBE45",
"description":"via Morris Park Av / Boston Rd",
"longName":"Westchester Sq - Mott Haven",
"shortName":"Bx21",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx021cur.pdf"},
{"id":"MTA NYCT_BX20",
"textColor":"FFFFFF",
"color":"00AEEF",
"description":"via Broadway / Henry Hudson Pkwy",
"longName":"Riverdale - Inwood",
"shortName":"Bx20",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx020cur.pdf"},
{"id":"MTA NYCT_BX22",
"textColor":"FFFFFF",
"color":"EE352E",
"description":"via Castle Hill Av",
"longName":"Bedford Park - Castle Hill",
"shortName":"Bx22",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx022cur.pdf"},
{"id":"MTA NYCT_BX12+",
"textColor":"FFFFFF",
"color":"006CB7",
"description":"Select Bus Service via Pelham Pkwy / Fordham Rd / Bay Plaza Shop Ctr",
"longName":"Pelham Pkwy - Fordham Rd",
"shortName":"Bx12-SBS",
"type":"3",
"agencyId":"MTA NYCT",
"url":"http://www.mta.info/nyct/bus/schedule/bronx/bx012scur.pdf"}

]




exports.getRoutes = function() {
	return routes;
}

exports.getRoute = function(id) {
	for(var i=0; i<routes.length; i++) {
		if(routes[i].id == id) return routes[i];
	}
}